### ISSUE TITLE
Elysian Drop Troops Army List

### ISSUE THREAD

**Issue by WindstormSCR** [BSData/wh40k-mobile-format#15]
Add to Astra_Militarum with regiment logic

**Comment by Ponha** [comment]
So I have been waiting for this since release of FW index. Since you seem to have a lot to do I wrote it my self today. Parts of it is not working as I want though. I cant for the life of me get the hide/show regiment selection and forgeworld logic to work.

I tried copying the versions that exist in the repo already for Pask and other hidden/shown entries.

To start out it says:
-- set Hidden to true
--- If Equal to 0 Selections in Force of Cadian

This logic makes perfect sense to me. As i click on the "If Equal..." item the Cadian part simply vanishes. I have tried locating Elysian under "Force" for my own entries but it does not exist there. I then copied the remaining logic from Pask and found Elysian under 'Faction but my set hidden logic seems to have zero effect from this. 

Could you help me out?

**Comment by Ponha** [comment]
So i solved it kind of, had to copy paste the id from "Elysian" and then not click it again, but its working. Will spend time polishing stuff and then see if i can understand how to submit a draft.

**Comment by Ponha** [comment]
issue is solved in latest pullrequest (#75)
