### ISSUE TITLE
Sisters of Sipence profiles and rules

### ISSUE THREAD

**Issue by Marina42** [BSData/wh40k-mobile-format#37]
They have points and options but the roster doesn’t show any profile nor rules

**Comment by WindstormSCR** [comment]
This is intentional, the points costs and selection logic for all units is being done first, then the profile data and rules are being added, once the FW indexes are entered the rest of the profile work will be done. 

the FAQ page explains why: https://github.com/BSData/wh40k-mobile-format/wiki/FAQs
